# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161104_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='repository',
        ),
        migrations.AddField(
            model_name='history',
            name='changes',
            field=models.ManyToManyField(to='main.Change'),
        ),
    ]
