# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161104_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='changes',
        ),
        migrations.AddField(
            model_name='change',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.History'),
        ),
    ]
