# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161104_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='change',
            name='current_file',
        ),
        migrations.RemoveField(
            model_name='change',
            name='history',
        ),
        migrations.RemoveField(
            model_name='change',
            name='previous_file',
        ),
        migrations.RemoveField(
            model_name='changeset',
            name='history',
        ),
        migrations.RemoveField(
            model_name='changeset',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='file',
            name='repository',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='workspace',
            new_name='local_copy',
        ),
        migrations.DeleteModel(
            name='Change',
        ),
        migrations.DeleteModel(
            name='ChangeSet',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
